# デバック用

# 制御周波数[Hz]
hz: 10              # ループ周波数 [Hz]

# carrot
dist_to_carrot1: 0.1  # carrot1（cmd_vel計算用ターゲット） [m]
dist_to_carrot2: 0.5  # carrot2（ステア角計算用ターゲット） [m]

# CCV
max_target_velocity: 1.2  # 目標並進速度 [m/s]
max_yawrate: 4.5          # 最高旋回速度 [rad/s]
max_steer_angle: 20.0     # ステア角の最大値 [deg]
tread: 0.5                # CCVのトレッド幅 [m]

# 許容誤差
goal_tolerance: 0.5  # ゴールに対する許容誤差 [m]

# 速度
vel_reso: 0.1  # 並進速度を計算するときの刻み幅 [m/s]
# 予測時間
dt: 0.1            # 微小時間 [s]
predict_time: 1.0  # 予測時間 [s]

# 評価関数関連
margin: 0.55  # 障害物とロボットの衝突半径（マージン込み） [m]

# frame_id
world_frame_id: "odom"            # 目標軌道
robot_frame_id: "base_footprint"  # ロボット